using System;
using System.Collections.Generic;
using System.Text;

namespace DapperOrm.Model
{
    /// <summary>
    /// 用于建立实体类与数据库表名的映射
    /// </summary>
    [AttributeUsage(AttributeTargets.Class)]
    public class OrmTableAttribute : System.Attribute
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="tableName"></param>
        public OrmTableAttribute(string tableName)
        {
            TableName = tableName;
            IsAutoGeneratedId = true;
        }
        /// <summary>
        ///  构造函数
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="idField"></param>
        public OrmTableAttribute(string tableName, string idField)
        {
            TableName = tableName;
            IdField = idField;
            IsAutoGeneratedId = true;
        }
        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <param name="idField">Id列名 </param>
        /// <param name="isAutoGeneratedId"></param>
        public OrmTableAttribute(string tableName, string idField, bool isAutoGeneratedId)
        {
            TableName = tableName;
            IdField = idField;
            IsAutoGeneratedId = isAutoGeneratedId;
        }
        /// <summary>
        /// 表名
        /// </summary>
        public string TableName { get; set; }

        /// <summary>
        /// 哪个字段是自增Id
        /// </summary>
        public string IdField{get;set;}
       
        /// <summary>
        /// 是否是自动产生的ID
        /// </summary>
        public bool IsAutoGeneratedId { get; set; }
    }
}
